# Generated by Django 5.1.6 on 2025-04-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_insuranceprovider_servicetype_insurancepolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='accounts.appointment'),
        ),
    ]
