# Generated by Django 3.2.25 on 2025-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.CharField(default='accounts/images/default.jpg', max_length=255),
        ),
    ]
